name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: |
        npm install
        npm install --prefix ./frontend
        npm install --prefix ./backend

    - name: Build
      run: npm run build --prefix ./frontend
  
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          npm install --prefix ./frontend
          npm install --prefix ./backend

      - name: Lint
        run: npx biome check --colors=off

      - name: Tests
        run: |
          npm run test --prefix ./frontend

  deploy:
    name: Deploy
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install dependencies
        run: |
          npm install
          npm install --prefix ./frontend
          npm install --prefix ./backend
          npm install --save-dev wrangler@4.14.4

      - name: Build
        run: npm run build --prefix ./frontend

      - name: frontend deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./frontend/dist --project-name=frontend --branch=main
        
      - name: backend deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --minify ./backend/src/index.ts