name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies and run tests
      run: |
        npm install
        npm install --prefix ./frontend
        npm install --prefix ./backend
  
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Lint
        run: npx biome check --colors=off

      - name: Tests
        run: |
          npm run test